from .crypto import register_get_crypto
from .crypto_json import register_get_crypto_json
from .crypto_xml import register_get_crypto_xml
from .fiat import register_get_fiat
from .fiat_json import register_get_fiat_json
from .fiat_xml import register_get_fiat_xml
from .menu import register_menu
from .pln_answer import register_answer_pln
from .pln_buy import register_buy_pln
from .pln_json import register_get_pln_json
from .pln_sell import register_sell_pln
from .pln_xml import register_get_pln_xml
