from .crypto import register_get_crypto
from .crypto_get import register_get_crypto_file
from .fiat import register_get_fiat
from .fiat_get import register_get_fiat_file
from .fcd_answer import register_get_answer_fcd
from .fcd_question import register_write_name_fcd
from .fcd_get import register_get_fcd
from .menu import register_menu
from .pln_answer import register_answer_pln
from .pln_buy import register_buy_pln
from .pln_sell import register_sell_pln
from .pln_get import register_get_pln_file
