version: '3.3'

services:
  bot:
    image: "bot"
    container_name: "bot-container"
    stop_signal: SIGINT
    build:
      context: .
    working_dir: "/usr/src/app"
    volumes:
    - .:/usr/src/app
    command: python3 bot.py
    restart: always
    env_file:
      - ".env"
    networks:
    - tg_bot


networks:
  tg_bot:
    driver: bridge
